# Generated by Django 3.2.2 on 2021-10-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0003_auto_20211003_1713'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('puntos', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('jugador_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jugadores.jugador', verbose_name='Jugador')),
                ('torneo_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='torneos.torneo', verbose_name='Torneo')),
            ],
            options={
                'db_table': 'Puntos',
            },
        ),
    ]
