# Generated by Django 3.2.2 on 2021-10-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_jugador', models.TextField(blank=True, verbose_name='Nombre')),
                ('apellido_jugador', models.TextField(blank=True, verbose_name='Apellido')),
                ('sobre_nombre_jugador', models.TextField(blank=True, verbose_name='Sobrenombre')),
                ('foto_jugador', models.URLField(blank=True, verbose_name='Link de la foto del jugador')),
            ],
            options={
                'db_table': 'jugador',
            },
        ),
    ]
