# Generated by Django 3.2.2 on 2021-10-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Torneo',
            new_name='Jugador',
        ),
    ]
