# Generated by Django 3.2.2 on 2021-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_rename_torneo_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='apellido_jugador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto_jugador',
            field=models.URLField(blank=True, max_length=5000, verbose_name='Link de la foto del jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre_jugador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='sobre_nombre_jugador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sobrenombre'),
        ),
    ]
