# Generated by Django 3.2.2 on 2021-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_torneo', models.TextField(verbose_name='Torneo')),
            ],
            options={
                'db_table': 'torneo',
            },
        ),
    ]
