# Generated by Django 3.2.2 on 2021-10-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneo',
            options={'managed': False},
        ),
    ]
